version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql_container_etl
    restart: always
    environment:
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: "${mysql_pass}"
      MYSQL_DATABASE: "${mysql_db}"
    ports:
      - "3307:3306"  # Ensure this port is not in use
    volumes:
      - type: volume
        source: my_db
        target: /var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_container_etl
    restart: always
    ports:
      - "8080:8080"
volumes:
  my_db: